### ISSUE TITLE
Error on first run.

### ISSUE THREAD

**Issue by titounnes** [samsonasik/ci4-vue#7] opened 2023-03-04 06:08 UTC
I just tried to install it, without modifying anything. I am using php version 8.2.3. when I try to run 

php spark serve

I get error message like this line.

`HP Fatal error:  Uncaught Error: Undefined constant "CodeIgniter\CLI\ENVIRONMENT" in /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php:666
Stack trace:
#0 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php(707): CodeIgniter\CLI\CLI::streamSupports()
#1 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php(159): CodeIgniter\CLI\CLI::hasColorSupport()
#2 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php(1115): CodeIgniter\CLI\CLI::init()
#3 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(312): include_once('...')
#4 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile()
#5 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
#6 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/Console.php(49): CodeIgniter\Autoloader\Autoloader->loadClass()
#7 /home/tito/app/CodeIgniter4/ci4-vue/spark(54): CodeIgniter\CLI\Console->showHeader()
#8 {main}
  thrown in /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php on line 666

Fatal error: Uncaught Error: Undefined constant "CodeIgniter\CLI\ENVIRONMENT" in /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php:666
Stack trace:
#0 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php(707): CodeIgniter\CLI\CLI::streamSupports()
#1 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php(159): CodeIgniter\CLI\CLI::hasColorSupport()
#2 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php(1115): CodeIgniter\CLI\CLI::init()
#3 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(312): include_once('...')
#4 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(289): CodeIgniter\Autoloader\Autoloader->includeFile()
#5 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/Autoloader/Autoloader.php(267): CodeIgniter\Autoloader\Autoloader->loadInNamespace()
#6 /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/Console.php(49): CodeIgniter\Autoloader\Autoloader->loadClass()
#7 /home/tito/app/CodeIgniter4/ci4-vue/spark(54): CodeIgniter\CLI\Console->showHeader()
#8 {main}
  thrown in /home/tito/app/CodeIgniter4/ci4-vue/vendor/codeigniter4/framework/system/CLI/CLI.php on line 666`

**Comment by samsonasik** [comment] 2023-03-04 06:33
I can't reproduce locally with php 8.2, also tested ok with ci build https://github.com/samsonasik/ci4-vue/actions/runs/4329700720/jobs/7560429346

 The `CodeIgniter::detectEnvironment()` somehow not fill the `ENVIRONMENT` constant on your local dev. It possibly that spark and public/index.php need to be copied from vendor/codeigniter4/framework

**Comment by samsonasik** [comment] 2023-03-04 10:46
I just tagged 0.5.0 with committed composer.lock to have same dependency on composer install, and sync spark, public/index.php, and app/Config.

If the issue persist, it possibly autoload overlap somewhere, eg: php preload

**Closed** 2023-03-07 00:08 UTC
